### ISSUE TITLE
Line: 55, Column: 1 System.NoDataFoundException: Data Not Available: 

### ISSUE THREAD

**Issue by yadavnarveer** [benedwards44/Apex-for-Xero#2]
Hi Ben,

Thanks for your awesome code.

Have follow your steps and deployed the package in my production org and this is working fine and as expected.But when i deployed the package in sandbox and try to fetch contact etc it is giving error 

Line: 55, Column: 1
System.NoDataFoundException: Data Not Available: The data you were trying to access could not be found. It may be due to another user deleting the data or a system error. If you know the data is not deleted but cannot access it, please look at our <A href="javascript:openPopupFocusEscapePounds('https://help.salesforce.com/apex/htdoor?body=%2Ftrain%2FonlineSupport.jsp&loc=support&language=en_US&release=204.7.5&instance=CS31&showSplash=true', 'Help', 1024, 768, 'width=1024,height=768,resizable=yes,toolbar=yes,status=yes,scrollbars=yes,menubar=yes,directories=no,location=yes,dependant=no', false, false);" title="support (New Window)">support</a> page.

Can you please guide for same.

Regards
Narveer

**Comment by densonclan** [comment]
I have the same issue:


Line: 40, Column: 1
System.NoDataFoundException: Data Not Available: The data you were trying to access could not be found. It may be due to another user deleting the data or a system error. If you know the data is not deleted but cannot access it, please look at our support page.
--

**Comment by densonclan** [comment]
Seems to be related to signing into Xero

11:29:51.1 (101607813)|FATAL_ERROR|System.NoDataFoundException: Data Not Available: The data you were trying to access could not be found. It may be due to another user deleting the data or a system error. If you know the data is not deleted but cannot access it, please look at our <A href="javascript:openPopupFocusEscapePounds('https://login.salesforce.com/services/auth/sso/00D30000000XsfGEAS/HTAuthProvider?startURL=%252Fapex%252Fhtdoor%253Fbody%253D%25252Ftrain%25252FonlineSupport.jsp%2526loc%253Dsupport%2526language%253Den_US%2526release%253D210.11.4%2526instance%253DEU9&site=https%3A%2F%2Fhelp.salesforce.com', 'Help', 1024, 768, 'width=1024,height=768,resizable=yes,toolbar=yes,status=yes,scrollbars=yes,menubar=yes,directories=no,location=yes,dependant=no', false, false);" title="support (New Window)">support</a> page.

Class.System.Crypto.signWithCertificate: line 40, column 1
Class.XeroOAuthUtility.generateSignature: line 85, column 1
Class.XeroOAuthUtility.signRequest: line 42, column 1
Class.XeroCalloutUtility.executeCallout: line 54, column 1
Class.XeroAccountingApi.createContact: line 75, column 1
Class.SFtoXero.createContact: line 10, column 1
AnonymousBlock: line 1, column 1
AnonymousBlock: line 1, column 1

**Comment by densonclan** [comment]
Hi

I've found the solution to this, it seems the certificate has to be named XeroCertificate otherwise it will not work.

Thanks

Barry

**Comment by benedwards44** [comment]
Yep, and it even says that in the Setup guide 😀

**Comment by densonclan** [comment]
Hi Ben

Could you change the setup guide to make it clear that this is important. I did see the certificate name in the guide but didn't realise it was critical.

Might help others avoid making the same mistake I did.

Thanks

Barry

**Comment by Srilatha28** [comment]
Hi, 
I am just wondering which Certificate you are talking about? because I have not set any certificate here as you did not mention in the read me file.


Thanks,
